[package]
name = "rustamp"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
dirs = "7.0.0"
eframe = "0.36.2"
egui_extras = { version = "0.36", features = ["image"] }
lofty = "0.25.3"
rand = "0.10.2"
rfd = "0.17.2"
rodio = "0.22.2"
rustfft = "6.4.1"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
walkdir = "2.5.0"
